version: '3.3'
networks:
  lemp-network:
services:
   db:
     image: mysql:5.7
     container_name: my_containername
     ports:
       - "3308:3306"
     networks:
       - lemp-network
     volumes:
       - ./db:/var/lib/mysql
       - ./config/my.cnf:/etc/mysql/my.cnf
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 212224
       MYSQL_DATABASE: hi
       MYSQL_USER: hiuser
       MYSQL_PASSWORD: 212224

   nginx:
     depends_on:
       - php
     image: nginx:alpine
     networks:
       - lemp-network
     volumes:
       - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
       - ./www:/var/www/html
     ports:
       - "8000:80"
     restart: always

   php:
     container_name: php
     image: php:7.3-fpm-alpine
     networks:
       - lemp-network
     restart: always
     volumes:
       - ./www/:/var/www/html
     ports:
       - "9000:9000"
     expose:
       - "9000"

volumes:
    db_data: {}